### ISSUE TITLE
[🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by 165056821** [lich0821/WeChatRobot#38]
**使用环境（请补全下列信息）：**
- 操作系统：【Windows Server 2008 】
- 操作系统版本：【 64 位】
- Python 版本 【3.10】

**描述这个 bug**
google gemini的API接口调用失败
- 访问python sdk遇到问题

Traceback (most recent call last):
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 79, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\grpc\_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\grpc\_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.217.160.106:443: socket is null"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-16T00:55:14.7024441+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.217.160.106:443: socket is null"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\api_core\retry.py", line 207, in retry_target
    result = target()
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\api_core\timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 81, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:172.217.160.106:443: socket is null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\wechat\new\WeChatRobot\test_gemini.py", line 9, in <module>
    response = model.generate_content("The opposite of hot is")
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\generativeai\generative_models.py", line 243, in generate_content
    response = self._client.generate_content(request)
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\client.py", line 566, in generate_content
    response = rpc(
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\api_core\gapic_v1\method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\api_core\retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "D:\Python\wechat\new\WeChatRobot\venv\lib\site-packages\google\api_core\retry.py", line 226, in retry_target
    raise exceptions.RetryError(
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:172.217.160.106:443: socket is null

**Comment by lich0821** [comment]
@aki66938 老板，有人来报 BUG 了——虽然很明显那是他网络的问题。

**Comment by aki66938** [comment]
请问这是添加了socket代理吗？如果是的话，代理的方式暂不可用，建议本地全局。官方sdk未给出代理的方式，目前还在验证代理方案的可行性。如果验证完成，会提交新版本，敬请留意

**Comment by suhou** [comment]
问题一：按照最新更新的代理配置，我已经输入了key，机器人却只能回复我“你@我干嘛”。
问题二：我下载项目的源码，配置好以后，base文件夹里面的bard.py会报错，说找不到configuration，是不是因为configuration.py不在base文件里面呀

**Comment by aki66938** [comment]
修复了proxy为空会无法启动bard的bug，请试用新版本

**Comment by suhou** [comment]
所有的源码都是最新的了，然后我配置好了bard的key，proxy，model，prompt，我在config.yaml文件把其他模型都注释了，只留下bard部分，但是运行main以后我问他问题还是无法回复，过一分钟后python返回Receiving message error: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:172.217.160.106:443: socket is null

**Comment by aki66938** [comment]
503是客户端问题，报错提示了未知ip->172.217.160.106:443: socket is null。这个IP大概率是谷歌IP的或者是其前置服务端的IP（推测
因此，尝试一下其他连接方式吧，更换节点或者尝试全局。
