### ISSUE TITLE
打包时提示缺少sdk.dll,我记得之前一个评论关于打包的,里面提到了这个,这个评论现在没了,希望重发一遍这个

### ISSUE THREAD

**Issue by NiBuLiHai** [lich0821/WeChatRobot#77]
C:\Users\Administrator\Desktop\WeChatRobot-39.2.4.0\新建文件夹\main>main
2024-10-02 21:43:07 wcferry version: 39.2.4.0
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 379, in __init__
FileNotFoundError: Could not find module 'C:\Users\Administrator\Desktop\WeChatRobot-39.2.4.0\新建文件夹\main\_internal\wcferry\sdk.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 66, in <module>
  File "main.py", line 31, in main
  File "wcferry\client.py", line 80, in __init__
  File "ctypes\__init__.py", line 460, in LoadLibrary
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\Administrator\\Desktop\\WeChatRobot-39.2.4.0\\新建文件夹\\main\\_internal\\wcferry/sdk.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[PYI-7928:ERROR] Failed to execute script 'main' due to unhandled exception!

C:\Users\Administrator\Desktop\WeChatRobot-39.2.4.0\新建文件夹\main>

**Comment by parvparv** [comment]
WeChatFerry 项目的  releases  的zip文件里 有sdk.dll   估计是你需要的
